version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://miru_razvan:blinktalk_ipdp@blinktalk.pda51jc.mongodb.net/?retryWrites=true&w=majority&appName=BlinkTalk
    restart: unless-stopped
